CREATE USER Integrado2 IDENTIFIED BY "MDY3131.1nt3gr4d02"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER Integrado2 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO Integrado2;
GRANT "RESOURCE" TO Integrado2;
ALTER USER Integrado2 DEFAULT ROLE "RESOURCE";